version: '3'

services:

    backend:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        ports:
            - 8080:8080
        volumes:
            - ./backend:/var/www
    composer:
      image: composer/composer:php7
      command: install
      volumes: 
        - ./backend:/var/www/backend
      depends_on: 
        - backend
          
    frontend:
        image: httpd:2.4-alpine
        ports:
            - 80:80
        volumes:
            - ./frontend/public:/usr/local/apache2/htdocs/
         
    tests:
        image: php:7.4-cli
        volumes:
             - ./backend:/var/www
        working_dir: /var/www
        entrypoint: ./vendor/bin/phpunit  
        depends_on:
            - backend 
            
    docs:
        image: phpdoc/phpdoc
        volumes:
            - ./backend:/var/www
        working_dir: /var/www
        entrypoint: phpdoc run -d ./app -t ./public/phpdoc/
        depends_on:
            - backend 
            - tests